### PR TITLE
POST/PUT XML files instead of XML data

### PR DESCRIPTION
**Pull request by talkingmoose**
While working with a customer to migrate items between two JSS servers, we found parsed_result XML files larger than about 256 KB wouldn't POST or PUT when curling them to the server.

The original script reads the parsed_result files using **cat** in the first line and then uploads the data using **POST/PUT -d** in the following line.

```
xmlPost_user=`cat $parsedXML_user`
curl -k "$destinationJSS"JSSResource/accounts/userid/99999 --user "$destinationJSSuser:$destinationJSSpw" -H "Content-Type: text/xml" -X POST -d "$xmlPost_user"
```

Changed the script to simply **reference the file itself** in the first line and then upload the file, which has no size limit, by changing to **POST/PUT -T** in the following line:

```
xmlPost_user=$parsedXML_user
curl -k "$destinationJSS"JSSResource/accounts/userid/99999 --user "$destinationJSSuser:$destinationJSSpw" -H "Content-Type: text/xml" -X POST -T "$xmlPost_user"
```

Altogether, this modified 16 lines of the script.

### CODE REVIEW

**Comment by str8outtajc** [comment]
I'm looking at code now.  Looks good.  Have you noticed any speed differences overall?  Any drawbacks to posting files vs data?  I only did as data originally b/c that's what the guidance at the time (mostly from unofficial JAMF API docs) illustrated.

**Comment by str8outtajc** [comment]
I'm about to test now

**Comment by str8outtajc** [comment]
I pulled changes in to master.  Thanks again.  Do I need to credit any one else besides you?

**Comment by talkingmoose** [comment]
Great! Not sure if this adds any performance improvements, but performance certainly doesn't seem to be impacted. And you and I get our guidance from the same place. :-)

I wouldn't find these things without using your script to help my customers. One of my customers deserves credit for this too, but I need to ask permission to share his name. I'll post back.

**Comment by talkingmoose** [comment]
Credit also goes to @andyincali for this submission. Your script went a long way to helping us get items copied to another system. A big THANKS from both of us!

**Pull request merged**
