### PR TITLE
Add the option to migrate policies WITH group information along with …

### PR DESCRIPTION
**Pull request by Lotusshaney**
…warning about LDAP/AD servers.

I have hundrads of AD based groups and policies and needed to pull them over.  Add an option to do this right before the main policies migration

### CODE REVIEW

**Comment by str8outtajc** [comment]
@Lotusshaney -- I'm looking very closely at your code changes.  I will probably end up manually applying the changes because I have a new version that works with sites that I am about to post.  And that will screw up your pull request.  

I'm actually having a hard time remembering why I excluded those items in the first place.  

I assume you have used this successfully?

**Comment by Lotusshaney** [comment]
Hi

Yes I've used this to pull in over 100 policies with AD info attached for limits and exclusions and it worked fine

Da

**Comment by str8outtajc** [comment]
And the only trick was to make sure the JSS was talking to AD correctly first?

**Comment by Lotusshaney** [comment]
Yeah

**Comment by str8outtajc** [comment]
Thanks a ton

**Comment by Lotusshaney** [comment]
No problem. Thanks for the great tool. I'm only to pleased to help out

**Comment by str8outtajc** [comment]
So this is killing me now.  I swear that when I first wrote this - there were all kinds of problems with scoping in policies - user scoping, limitations, exclusions, etc.  For example, if you had a policy scoped to a specific computer, and a specific user (not from "account" / from "users") - that policy would not even make it to the destination, b/c the destination didn't know about the user.  The POST would fail completely.  But now it fails gracefully.  The POST works fine, and the destination is simply missing the user.   

I'm guessing there was a fix in the API somewhere along the way.

**Comment by Lotusshaney** [comment]
I have tested this going from 9.81 to a new 9.92 JSS without a problem. 

My guess is JAMF have fixed the API without telling anyone :)

**Comment by str8outtajc** [comment]
So I'm not going to pull this branch in.  I used your idea slightly differently.  Gave you credit in the updated README - https://github.com/igeekjsc/JSSAPIScripts/blob/master/README.md#whats-new

Thanks again !

**Pull request closed without merging**
